use_gpu: true
exp_name: ~

dataroot: ../../data

partition:
  choice: Dirichlet
  Dirichlet:
    beta: 0.5

comm_rounds: 100
local_epochs: 10
n_parties: 10
select_frac: 1.0
batch_size: 64

lr: 0.01
weight_decay: 0.00001
momentum: 0.9

save_per_rounds: ~
