use_gpu: true
exp_name: ~

dataroot: ../../data

partition:
  choice: Dirichlet
  Dirichlet:
    beta: 0.1
  NonIID:
    n_class_each_client: 2
  read_from_file:
    file_path: ./runs/beta0.1/idx_parties.txt

model: SimpleCNN  # modVGG / SimpleCNN

comm_rounds: 100
local_epochs: 10
n_parties: 10
select_frac: 1.0
batch_size: 64

naive_mix: false
mean_batch: 5
lambda: 0.05

lr: 0.01
weight_decay: 0.00001
momentum: 0.9

save_per_rounds: ~
